trigger:
- master

variables:
  config: Release

strategy:
  matrix:
    Linux:
      imageName: "ubuntu-18.04"
      generator: "Ninja"
      deps: |
        sudo apt-get -y update
        sudo apt-get -y install \
          build-essential \
          libsdl2-dev \
          qtbase5-dev \
          libqt5opengl5-dev \
          qtmultimedia5-dev \
          qttools5-dev \
          qttools5-dev-tools \
          libavcodec-dev \
          libavformat-dev \
          libswscale-dev \
          ninja-build
    Linux-MinGW:
      imageName: "ubuntu-18.04"
      generator: "Ninja"
      deps: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv '72931B477E22FEFD47F8DECE02FE5F12ADDE29B2'
        sudo add-apt-repository http://ppa.launchpad.net/tobydox/mingw-w64/ubuntu
        sudo apt-get -y update
        sudo apt-get -y install \
          g++-mingw-w64-x86-64 \
          gcc-mingw-w64-x86-64 \
          mingw-w64-tools \
          ninja-build \
          sdl2-mingw-w64 \
          qt5base-mingw-w64 \
          qt5tools-mingw-w64 \
          libsamplerate-mingw-w64 \
          qt5multimedia-mingw-w64
      defs: -DCMAKE_TOOLCHAIN_FILE="$(Build.SourcesDirectory)/CMakeModules/MinGWCross.cmake"
      run_tests: false
    MacOS:
      imageName: "macos-10.14"
      generator: "Ninja"
      deps: |
        brew update
        brew unlink python@2
        brew install sdl2 qt ffmpeg ninja
        pip3 install mac
      defs: -DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5
    Windows-MSVC:
      imageName: "windows-2019"
      generator: "Visual Studio 16 2019"
      deps: ""
      defs: ""
      run_tests: true
      shell: ""
      shell_end: ""
    Windows-MinGW:
      imageName: "windows-2019"
      generator: "MSYS Makefiles"
      deps: |
        git clone https://github.com/msys2/msys2-ci-base.git "$(Agent.BuildDirectory)/msys2"
        "$(Agent.BuildDirectory)/msys2/usr/bin/pacman" --noconfirm -Syyuu
        "$(Agent.BuildDirectory)/msys2/usr/bin/pacman" --noconfirm -S mingw-w64-x86_64-{gcc,SDL2,qt5,cmake} make
      shell: "\"$(Agent.BuildDirectory)/msys2/usr/bin/bash\" -lc '"
      shell_end: "'"

pool:
  vmImage: $(imageName)

steps:
- checkout: self
  submodules: recursive
- script: |
    mkdir build
    $(deps)
  displayName: Dependencies
- script: $(shell) cmake .. -G "$(generator)" -DCMAKE_BUILD_TYPE=$(config) $(defs) $(shell_end)
  displayName: Configure
  workingDirectory: build
- script: $(shell) cmake --build . --config $(config) $(shell_end)
  displayName: Build
  workingDirectory: build
- script: ctest -C $(config)
  displayName: Test
  workingDirectory: build
  condition: and(succeeded(), eq(variables.run_tests, 'true'))
- task: PublishPipelineArtifact@1
  displayName: Publish
  inputs:
    artifactName: $(Agent.JobName)
    targetPath: build/bin
