trigger:
- master

strategy:
  matrix:
    Linux:
      imageName: "ubuntu-latest"
      generator: "Ninja"
    MacOS:
      imageName: "macos-latest"
      generator: "Ninja"
    Windows-MSVC:
      imageName: "windows-latest"
      generator: "Visual Studio 16 2019"
    Windows-MinGW:
      imageName: "windows-latest"
      generator: "MSYS Makefiles"
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
- task: CMake@1
  displayName: Configure
  inputs:
    cmakeArgs: .. -G "$(generator)"
- task: CMake@1
  displayName: Build
  inputs:
    cmakeArgs: --build .
