on: [push, pull_request]
jobs:
  Citra:
    env:
      config: Release
      # Tell msys2 to add mingw64 to the path
      MSYSTEM: MINGW64
      # Tell msys2 to inherit the current directory when starting the shell
      CHERE_INVOKING: 1
    strategy:
      matrix:
        config:
          - name: Linux
            os: "ubuntu-18.04"
            generator: Ninja
            defs: -DCMAKE_MAKE_PROGRAM=ninja
            deps: |
              sudo apt-get -y update
              sudo apt-get -y install \
                cmake \
                build-essential \
                libsdl2-dev \
                qtbase5-dev \
                libqt5opengl5-dev \
                qtmultimedia5-dev \
                qttools5-dev \
                qttools5-dev-tools \
                libavcodec-dev \
                libavformat-dev \
                libswscale-dev \
                ninja-build
            run_tests: true
          - name: Linux-MinGW
            os: "ubuntu-18.04"
            generator: Ninja
            deps: |
              sudo apt-key adv --keyserver keyserver.ubuntu.com --recv '72931B477E22FEFD47F8DECE02FE5F12ADDE29B2'
              sudo add-apt-repository http://ppa.launchpad.net/tobydox/mingw-w64/ubuntu
              sudo apt-get -y update
              sudo apt-get -y install \
                cmake \
                g++-mingw-w64-x86-64 \
                gcc-mingw-w64-x86-64 \
                mingw-w64-tools \
                ninja-build \
                sdl2-mingw-w64 \
                qt5base-mingw-w64 \
                qt5tools-mingw-w64 \
                libsamplerate-mingw-w64 \
                qt5multimedia-mingw-w64
            defs: -DCMAKE_MAKE_PROGRAM=ninja -DCOMPILE_WITH_DWARF=OFF -DCMAKE_TOOLCHAIN_FILE="../CMakeModules/MinGWCross.cmake"
            run_tests: false

          - name: MacOS
            os: "macos-10.15"
            generator: Ninja
            deps: |
              brew update
              brew unlink python@2
              brew install sdl2 qt ffmpeg ninja
              pip3 install mac
            defs: -DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5 -DENABLE_FFMPEG_AUDIO_DECODER=ON
            run_tests: true

          - name: Windows-MSVC
            os: "windows-2019"
            generator: Ninja
            deps: |
              &{Import-Module "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"; Enter-VsDevShell eb767fea}
            run_tests: true

          - name: Windows-MinGW
            os: "windows-2019"
            generator: "MSYS Makefiles"
            deps: |
              git clone https://github.com/msys2/msys2-ci-base.git "./msys2"
              &"./msys2/usr/bin/pacman" --noconfirm -Syyuu
              &"./msys2/usr/bin/pacman" --noconfirm -S "mingw-w64-x86_64-{gcc,SDL2,qt5,cmake,ffmpeg}" make
            defs: '-j3'
            cmake_shell: '&"../msys2/usr/bin/bash" -lc "'
            shell_end: '"'
            run_tests: true
  
    runs-on: ${{matrix.config.os}}
    name: ${{matrix.config.name}}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          mkdir build
          ${{matrix.config.deps}}
        name: Dependencies
      - run: ${{matrix.config.cmake_shell}} cmake .. -G '${{matrix.config.generator}}'
          -DCMAKE_BUILD_TYPE=${{env.config}}
          -DBUILD_REPOSITORY=${{github.repository}}
          -DBUILD_TAG=${{github.ref}}
          -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON
          -DUSE_DISCORD_PRESENCE=ON
          -DENABLE_FFMPEG_VIDEO_DUMPER=ON
          -DCITRA_ENABLE_COMPATIBILITY_REPORTING=${{github.branch == 'master' && github.repository == 'citra-emu/citra'}}
          ${{matrix.config.defs}} ${{matrix.config.shell_end}}
        name: Configure
        working-directory: build
      - run: ${{matrix.config.cmake_shell}} cmake --build . --config ${{env.config}} ${{matrix.config.shell_end}}
        name: Build
        working-directory: build
      - run: ctest -C ${{env.config}}
        name: Test
        working-directory: build
        if: matrix.config.run_tests
      - uses: actions/upload-artifact@v1
        name: Publish
        with:
          name: ${{matrix.config.name}}
          path: build/bin
